spring.application.name=redis
server.port=6678

spring.profiles.active=prod
jwt.secret=l16fpKlpvp0gqUg0RoYVjpLatnTXxF33DtiGQUWYF6g


#kafka configuration..

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer: Receiving JSON data (if needed in the same app)
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Crucial for the consumer to accept your JSON objects
spring.kafka.consumer.properties.spring.json.trusted.packages=*


# Optional: If you want to completely ignore the type headers from the producer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.auto-offset-reset=earliest

#--Db Configuration

#Circuitbreakerconfiguration.
resilience4j.circuitbreaker.instances.orderservice.sliding-window-size=10
resilience4j.circuitbreaker.instances.orderservice.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderservice.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.orderservice.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.orderservice.wait-duration-in-open-state=10000